# Generated by Django 2.0.5 on 2018-05-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('education', models.CharField(blank=True, max_length=45, null=True)),
                ('job', models.CharField(blank=True, max_length=45, null=True)),
                ('annual_income', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'MemberCentre',
                'managed': True,
            },
        ),
    ]
