# Generated by Django 2.0.5 on 2018-06-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etfPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opend', models.DecimalField(decimal_places=2, max_digits=6)),
                ('close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Volume', models.IntegerField()),
            ],
            options={
                'db_table': 'etfPrices',
            },
        ),
        migrations.CreateModel(
            name='etfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=8)),
                ('etfName', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('usStock', 'usStock'), ('worldStock', 'worldStock'), ('emerStock', 'emerStock'), ('sectorStock', 'sectorStock'), ('usBond', 'usBond'), ('worldBond', 'worldBond')], max_length=20)),
                ('expenseRatio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('YTDreturn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yrReturn1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yrReturn3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yrReturn5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('StdDev', models.DecimalField(decimal_places=2, max_digits=6)),
                ('SharpeRatio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'etfs',
            },
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('targetFV', models.IntegerField()),
                ('risk', models.CharField(max_length=20)),
                ('startDeposit', models.IntegerField()),
                ('monthlyDeposit', models.IntegerField()),
                ('usStock', models.CharField(max_length=10)),
                ('worldStock', models.CharField(max_length=10)),
                ('emerStock', models.CharField(max_length=10)),
                ('sectorStock', models.CharField(max_length=10)),
                ('usBond', models.CharField(max_length=10)),
                ('worldBond', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.AddField(
            model_name='etfprices',
            name='Ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.etfs'),
        ),
    ]
