# Generated by Django 2.0.5 on 2018-05-30 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etfPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opend', models.DecimalField(decimal_places=2, max_digits=6)),
                ('close', models.DecimalField(decimal_places=2, max_digits=6)),
                ('high', models.DecimalField(decimal_places=2, max_digits=6)),
                ('low', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Volume', models.IntegerField()),
            ],
            options={
                'db_table': 'etfPrices',
            },
        ),
        migrations.CreateModel(
            name='etfs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=8)),
                ('etfName', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('usStock', 'usStock'), ('worldStock', 'worldStock'), ('emerStock', 'emerStock'), ('sectorStock', 'sectorStock'), ('usBond', 'usBond'), ('worldBond', 'worldBond')], max_length=8)),
                ('expenseRatio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('YTDreturn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yrReturn1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yrReturn3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yrReturn5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('StdDev', models.DecimalField(decimal_places=2, max_digits=6)),
                ('SharpeRatio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'etfs',
            },
        ),
        migrations.CreateModel(
            name='MemberCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('cellphone', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('education', models.CharField(blank=True, max_length=45, null=True)),
                ('job', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'MemberCentre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(choices=[('retire', 'retire'), ('education', 'education'), ('house', 'house'), ('travel', 'travel'), ('wedding', 'wedding'), ('other', 'other')], max_length=10)),
                ('duration', models.IntegerField()),
                ('targetFV', models.IntegerField()),
                ('risk', models.CharField(choices=[('low', 'low'), ('med', 'medium'), ('high', 'high')], max_length=4)),
                ('startDeposit', models.IntegerField()),
                ('monthlyDeposit', models.IntegerField()),
                ('usStock', models.CharField(max_length=10)),
                ('usStockPct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('worldStock', models.CharField(max_length=10)),
                ('worldStockPct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('emerStock', models.CharField(max_length=10)),
                ('emerStockPct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sectorStock', models.CharField(max_length=10)),
                ('sectorStockPct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usBond', models.CharField(max_length=10)),
                ('usBondPct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('worldBond', models.CharField(max_length=10)),
                ('worldBondPct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('memberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.MemberCentre')),
            ],
            options={
                'db_table': 'portfolio',
            },
        ),
        migrations.AddField(
            model_name='etfprices',
            name='Ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.etfs'),
        ),
    ]
