# Generated by Django 2.0.5 on 2018-05-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('姓名', models.CharField(max_length=20)),
                ('學歷', models.CharField(max_length=100)),
                ('經歷', models.CharField(max_length=100)),
                ('證照', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'consultants',
            },
        ),
    ]
